export const initialData = {
  sea: [
    { code: 'nao' },
    { code: 'nwg' },
    { code: 'bar' },
    { code: 'nth' },
    { code: 'ska' },
    { code: 'iri' },
    { code: 'bot' },
    { code: 'hel' },
    { code: 'bal' },
    { code: 'eng' },
    { code: 'mao' },
    { code: 'lyo' },
    { code: 'tys' },
    { code: 'adr' },
    { code: 'wes' },
    { code: 'bla' },
    { code: 'aeg' },
    { code: 'ion' },
    { code: 'eas' }
  ],
  land: [
    { code: 'cly', owner: 'e' },
    { code: 'edi', owner: 'e' },
    { code: 'lvp', owner: 'e' },
    { code: 'yor', owner: 'e' },
    { code: 'wal', owner: 'e' },
    { code: 'lon', owner: 'e' },
    { code: 'bre', owner: 'f' },
    { code: 'pic', owner: 'f' },
    { code: 'par', owner: 'f' },
    { code: 'bur', owner: 'f' },
    { code: 'gas', owner: 'f' },
    { code: 'mar', owner: 'f' },
    { code: 'kie', owner: 'g' },
    { code: 'ber', owner: 'g' },
    { code: 'pru', owner: 'g' },
    { code: 'ruh', owner: 'g' },
    { code: 'mun', owner: 'g' },
    { code: 'sil', owner: 'g' },
    { code: 'pie', owner: 'i' },
    { code: 'ven', owner: 'i' },
    { code: 'tus', owner: 'i' },
    { code: 'rom', owner: 'i' },
    { code: 'apu', owner: 'i' },
    { code: 'nap', owner: 'i' },
    { code: 'tyr', owner: 'a' },
    { code: 'boh', owner: 'a' },
    { code: 'gal', owner: 'a' },
    { code: 'vie', owner: 'a' },
    { code: 'tri', owner: 'a' },
    { code: 'bud', owner: 'a' },
    { code: 'fin', owner: 'r' },
    { code: 'stp', owner: 'r' },
    { code: 'liv', owner: 'r' },
    { code: 'war', owner: 'r' },
    { code: 'mos', owner: 'r' },
    { code: 'ukr', owner: 'r' },
    { code: 'sev', owner: 'r' },
    { code: 'con', owner: 't' },
    { code: 'ank', owner: 't' },
    { code: 'smy', owner: 't' },
    { code: 'arm', owner: 't' },
    { code: 'syr', owner: 't' },
    { code: 'nwy', owner: null },
    { code: 'swe', owner: null },
    { code: 'den', owner: null },
    { code: 'hol', owner: null },
    { code: 'bel', owner: null },
    { code: 'spa', owner: null },
    { code: 'por', owner: null },
    { code: 'naf', owner: null },
    { code: 'tun', owner: null },
    { code: 'alb', owner: null },
    { code: 'ser', owner: null },
    { code: 'gre', owner: null },
    { code: 'rum', owner: null },
    { code: 'bul', owner: null }
  ],
  unit: [
    { code: 'lon', kind: 'f', owner: 'e' },
    { code: 'edi', kind: 'f', owner: 'e' },
    { code: 'lvp', kind: 'a', owner: 'e' },
    { code: 'par', kind: 'a', owner: 'f' },
    { code: 'bre', kind: 'f', owner: 'f' },
    { code: 'mar', kind: 'a', owner: 'f' },
    { code: 'ber', kind: 'a', owner: 'g' },
    { code: 'kie', kind: 'f', owner: 'g' },
    { code: 'mun', kind: 'a', owner: 'g' },
    { code: 'rom', kind: 'a', owner: 'i' },
    { code: 'ven', kind: 'a', owner: 'i' },
    { code: 'nap', kind: 'f', owner: 'i' },
    { code: 'vie', kind: 'a', owner: 'a' },
    { code: 'bud', kind: 'a', owner: 'a' },
    { code: 'tri', kind: 'f', owner: 'a' },
    { code: 'mos', kind: 'a', owner: 'r' },
    { code: 'stp_sc', kind: 'f', owner: 'r' },
    { code: 'war', kind: 'a', owner: 'r' },
    { code: 'sev', kind: 'f', owner: 'r' },
    { code: 'con', kind: 'a', owner: 't' },
    { code: 'ank', kind: 'f', owner: 't' },
    { code: 'smy', kind: 'a', owner: 't' }
  ]
};
